# Macro file for example B4
#
# To be run preferably in batch, without graphics:
# % exampleB4[a,b,c,d] run2.mac
#
#/run/numberOfThreads 4
#/control/cout/ignoreThreadsExcept 0
#
/run/initialize
#
# Incident energy range (uniform continuous sampling between emin and emax)
/B4/gun/emin 1 GeV
/B4/gun/emax 100 GeV
#
# Output ROOT file
/B4/run/outputFile photon_showers.root
#
/run/printProgress 100
/gun/particle gamma
/run/beamOn 5000

